name: Bazel CI
on: [push, pull_request, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: bazel-contrib/.github/.github/workflows/bazel.yaml@v7
    with:
      folders: |
        [
          ".",
          "bazel/integration_test",
        ]
      exclude: |
        [
          {"folder": ".", "bzlmodEnabled": false},
          {"folder": "bazel/integration_test", "bzlmodEnabled": false},
        ]
